### ISSUE TITLE
home page design issues

### ISSUE THREAD

**Issue by mckennapsean** [visdesignlab/visdesignlab.github.io#16]
as Nina said, this needs "smoothing". there is a pixel off on the bottom-right header image. I don't think this is randomly grabbing images. we may need high-res images of recent papers (maybe only get papers from the past year for this too?). feel free to comment on additional design tweaks below.

**Comment by ninaMc** [comment]
The banner images currently show the three latest pubs: big image shows the latest pub, smaller images show 2nd and 3rd latest pubs. I thought this was the plan, but we can certainly change this to random.

**Comment by mckennapsean** [comment]
ohhh, gotcha! I just thought people had talked about those images being random. I could totally be wrong. doesn't matter to me. :-)

**Comment by alexsb** [comment]
Afair the plan was to pick random images from the last n years. I don't think we should just keep the latest papers on there because this will just over-represent some papers, while others don't get shown at all. Especially, when we publish multiple papers at the same time (think VIS), some would get completely left out.

**Comment by ninaMc** [comment]
Yes, totally agree! I'll make the change. Thanks guys.

**Comment by mckennapsean** [comment]
thank you Nina! there are also some issues for responsive design. I have made a separate issue for this.

**Comment by samquinan** [comment]
Home page design should be fine at this point.
