### ISSUE TITLE
Duplicate images when adding a publication

### ISSUE THREAD

**Issue by mckennapsean** [visdesignlab/visdesignlab.github.io#56]
We have told people to add their publication images to this repo, but also into the `/usr/sci/www/vdl/papers` directory. From what I can tell, all of the images on the VDL site come from the repo, not from the SCI server. Is there a reason images are stored there redundantly though? I can keep the requirement if needed, but we can save space & people's time by removing that otherwise.

Another alternative is to put full-size, uncompressed images on the SCI server. Then _**only**_ put the compressed versions of images on the repository. These could be used as a backup or for recompressing all site images in the future. I can get things copied over there, as I am working on compressing our images now.

**Comment by alexsb** [comment]
I'm aware of that, but I'd like to keep it like that. Having the main images on github makes sense because of the CDN. Having the images in the folder makes sense for consistency - all files for a paper are in the same folder. I use this folder a lot if I want quick access to paper materials. And I think it's very little overhead.
