### ISSUE TITLE
Increase width of layout

### ISSUE THREAD

**Issue by alexsb** [visdesignlab/visdesignlab.github.io#7]
Right now it's 750 pixels, but that's very narrow. I'd suggest at least 1024, maybe even 1200.

**Comment by mckennapsean** [comment]
A max width of 1024/1080 - 1200 perhaps. This should not be the only/default width, as there are plenty of people with laptops that would have to scroll horizontally on our page to see the content. Currently, the page is fixed with width (so no real responsive design). I will see what I can do easily. We should definitely allow the webpage to grow to a certain amount of space rather than being stuck in 750px.

**Comment by mckennapsean** [comment]
Alrighty! I did just that. I figured we can have a large display size (1200px) and medium (750px) as well as a small one (300px). There are a few tweaks to make for all of these, but everything is showing up at all resolutions!
